services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "1234:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: